export const TOGGLE_SIDE_BAR = "TOGGLE_SIDE_BAR";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";

export const SET_GROUP_STAGE = "SET_GROUP_STAGE";

export const CHANGE_CLUB_POWER = "CHANGE_CLUB_POWER";

export const WIN_THE_MATCH = "WIN_THE_MATCH";
export const LOOSE_THE_MATCH = "LOOSE_THE_MATCH";
export const DRAW_THE_MATCH = "DRAW_THE_MATCH";

export const ADD_OPENED_MATCH = "ADD_OPENED_MATCH";

export const OPEN_DAYS = "OPEN_DAYS";

export const SET_TOURNAMENT_GROUP = "SET_TOURNAMENT_GROUP";

export const SET_FIRST_SELECTABLE = "SET_FIRST_SELECTABLE";
export const SET_SECOND_SELECTABLE = "SET_SECOND_SELECTABLE";

export const SET_TOURNAMENT_16 = "SET_TOURNAMENT_16";

export const SET_BOARD = "SET_BOARD";
